version: "3.6"

services:
  db:
    image: mongo
    ports:
      - 27017:27017
  seeder:
    build:
      context: ./
      dockerfile: ./src/services/DBSeeder/Dockerfile
    depends_on:
      - db
    environment:
      - DB_URI=mongodb://db:27017
      - DB_NAME=dev
    command: sh -c "/usr/local/bin/wait-for-it.sh db:27017 -- npm run run-seeder"
