version: "3.6"

services:
  db:
    image: mongo
    ports:
      - 27017:27017
  seeder:
    build:
      context: ./
      dockerfile: ./src/services/DBSeeder/Dockerfile
    depends_on:
      - db
    environment:
      - DB_URI=mongodb://db
      - DB_NAME=dev
      - DB_PORT=27017
      - DB_USER_NAME=
      - DB_USER_PASSWORD=
    command: sh -c "/usr/local/bin/wait-for-it.sh db:27017 -- npm run seedDB"
